# Laravel Cloud Configuration
name: vgentech

# PHP Version
php: "8.3"

# Build Commands
build:
  - composer install --no-dev --optimize-autoloader
  - npm ci
  - npm run build
  - php artisan config:cache
  - php artisan route:cache
  - php artisan view:cache

# Deploy Commands
deploy:
  - php artisan migrate --force
  - php artisan storage:link

# Environment Variables (set in Laravel Cloud dashboard)
# APP_NAME=VgenTech
# APP_ENV=production
# APP_DEBUG=false
# APP_URL=https://your-domain.com
# DB_CONNECTION=pgsql
# DB_HOST=
# DB_PORT=5432
# DB_DATABASE=
# DB_USERNAME=
# DB_PASSWORD=

# Cron Jobs
schedule:
  - command: "php artisan schedule:run"
    frequency: "* * * * *"

# Queue Workers
queues:
  - connection: database
    queue: default
    processes: 1
    tries: 3
    timeout: 60

# Storage
storage:
  - storage/app/public
  - storage/logs
